### ISSUE TITLE
win10有道生词本同步出错

### ISSUE THREAD

**Issue by wstsfd** [megachweng/Dict2Anki#1]
一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\76912\AppData\Roaming\Anki2\addons\Dick2Anki.py", line 174, in sync
    current = self.getCurrent()
  File "C:\Users\76912\AppData\Roaming\Anki2\addons\Dick2Anki.py", line 226, in getCurrent
    DB = self.youdaoDB
AttributeError: 'Window' object has no attribute 'youdaoDB'

代码226行要找youdaoDB,但是无法找到目标，我检查了一下我的系统也的确没有这个Database? 不知道如何解决。

不是计算机专业看不大懂，也是第一次来这个网站有点搞不太懂代码。打扰了

**Comment by megachweng** [comment]
已经尝试修复，请到`https://github.com/megachweng/Dict2Anki/releases/tag/v1.0`下载最新版本覆盖
如果有问题欢迎提issue
