### ISSUE TITLE
今天才安装的插件，不能用，启动anki就弹出错误代码

### ISSUE THREAD

**Issue by hahamax** [megachweng/Dict2Anki#13]
一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt\addons.py", line 41, in loadAddons
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\PluginEntry.py", line 11, in <module>
    from Dict2Anki.window import Window
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\Dict2Anki\window.py", line 22, in <module>
    ssl._create_default_https_context = ssl._create_unverified_context
AttributeError: 'module' object has no attribute '_create_unverified_context'

**Comment by megachweng** [comment]
能提供一下anki版本和操作系统版本吗
