### ISSUE TITLE
go wrong at the end of synchronization, Win10  Anki Ver.2.050

### ISSUE THREAD

**Issue by sthxp** [megachweng/Dict2Anki#17]
it occurs wrong warning and fails in synchronizing with Eudic. please fix this :)

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "D:\Program Files (x86)\Anki\ankidata\addons\Dict2Anki\window.py", line 302, in __startSync
    self.__processNote(self.lookUpedTerms,self.comparedWordList['deleted'])
  File "D:\Program Files (x86)\Anki\ankidata\addons\Dict2Anki\window.py", line 411, in __processNote
    Note(lookUpedTerms,deleteWords,syncSettings).processNote(self.syncTo.currentText())
  File "D:\Program Files (x86)\Anki\ankidata\addons\Dict2Anki\note.py", line 131, in processNote
    note['term'] = term['term']
  File "anki\notes.py", line 101, in __setitem__
  File "anki\notes.py", line 95, in _fieldOrd
KeyError: 'term'

**Comment by fqzhou** [comment]
Something wrong...

Traceback (most recent call last):
  File "aqt\addons.py", line 41, in loadAddons
  File "C:\Users\fqzhou\AppData\Roaming\Anki2\addons\PluginEntry.py", line 11, in <module>
    from Dict2Anki.window import Window
  File "C:\Users\fqzhou\AppData\Roaming\Anki2\addons\Dict2Anki\window.py", line 22, in <module>
    ssl._create_default_https_context = ssl._create_unverified_context
AttributeError: 'module' object has no attribute '_create_unverified_context'

**Comment by Bryantjialu** [comment]
@sthxp 
@fqzhou 
Please make sure your deck's default template is provided by the addon (Dict2Anki).
Otherwise it will cause this problem.
