### ISSUE TITLE
你好，安装了最新版3.0，出现如下代码不能运行

### ISSUE THREAD

**Issue by mollyzio** [megachweng/Dict2Anki#22]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\Dict2Anki\window.py", line 302, in __startSync
    self.__processNote(self.lookUpedTerms,self.comparedWordList['deleted'])
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\Dict2Anki\window.py", line 411, in __processNote
    Note(lookUpedTerms,deleteWords,syncSettings).processNote(self.syncTo.currentText())
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\Dict2Anki\note.py", line 135, in processNote
    note['uk'] = term['uk']
  File "anki\notes.py", line 101, in __setitem__
  File "anki\notes.py", line 95, in _fieldOrd
KeyError: 'uk'

**Comment by Bryantjialu** [comment]
@mollyzio 
请确保你在导入时，对应的记忆库的默认模板使用的是插件提供的模板Dict2Anki，否则会报错
