### ISSUE TITLE
anki导入时报错，希望您可以抽空解决一下，谢谢

### ISSUE THREAD

**Issue by DrSkyeagle** [megachweng/Dict2Anki#23]
Traceback (most recent call last):
File "D:\Program Files (x86)\Anki\ankidata\addons\Dict2Anki\window.py", line 302, in __startSync
self.__processNote(self.lookUpedTerms,self.comparedWordList['deleted'])
File "D:\Program Files (x86)\Anki\ankidata\addons\Dict2Anki\window.py", line 411, in __processNote
Note(lookUpedTerms,deleteWords,syncSettings).processNote(self.syncTo.currentText())
File "D:\Program Files (x86)\Anki\ankidata\addons\Dict2Anki\note.py", line 131, in processNote
note['term'] = term['term']
File "anki\notes.py", line 101, in setitem
File "anki\notes.py", line 95, in _fieldOrd
KeyError: 'term'

**Comment by megachweng** [comment]
最近公司事情比较多，会尽快debug一下，望谅解

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Bryantjialu** [comment]
报错相同，请尽快解决，谢谢！

**Comment by Bryantjialu** [comment]
@DrSkyeagle 
问题已解决，请确保你在导入时，对应的记忆库的默认模板使用的是插件提供的模板Dict2Anki，否则会报错
