### ISSUE TITLE
win10 ，2.0.51 报错，不清楚是我的问题还是欧陆改了接口

### ISSUE THREAD

**Issue by www123321** [megachweng/Dict2Anki#25]
麻烦您有空时看一下
非常感谢
Traceback (most recent call last):
  File "C:\Users\whd\AppData\Roaming\Anki2\addons\Dict2Anki\worker.py", line 62, in run
    response = urllib2.urlopen(req).read()
  File "urllib2.py", line 154, in urlopen
  File "urllib2.py", line 435, in open
  File "urllib2.py", line 548, in http_response
  File "urllib2.py", line 473, in error
  File "urllib2.py", line 407, in _call_chain
  File "urllib2.py", line 556, in http_error_default
urllib2.HTTPError: HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "C:\Users\whd\AppData\Roaming\Anki2\addons\Dict2Anki\window.py", line 298, in __startSync
    self.currentWordList = self.__getCurrentWordList()
  File "C:\Users\whd\AppData\Roaming\Anki2\addons\Dict2Anki\window.py", line 325, in __getCurrentWordList
    results = self.dictThread.results
AttributeError: 'Eudict' object has no attribute 'results'

**Comment by gdd111** [comment]
Please make sure your deck's default template is provided by the addon (Dict2Anki).
Otherwise it will cause this problem.
默认模板改成：Dict2Anki
