### ISSUE TITLE
同步时报错

### ISSUE THREAD

**Issue by yuanzhiqee** [megachweng/Dict2Anki#26]
您好！使用Anki-2.0.51和最新的Dict2Anki同步欧陆词典单词，总是有如下错误

Traceback (most recent call last):
  File "C:\Users\Yuanzhi\AppData\Roaming\Anki2\addons\Dict2Anki\window.py", line 297, in __startSync
    self.lastWordList = self.__getLastWordList()
  File "C:\Users\Yuanzhi\AppData\Roaming\Anki2\addons\Dict2Anki\window.py", line 334, in __getLastWordList
    cursor.execute("select terms from history where deck='%s' and dictionary = '%d' order by id desc limit 0, 1" % (deck, dictionary))
sqlite3.OperationalError: no such column: deck

**Comment by gdd111** [comment]
Please make sure your deck's default template is provided by the addon (Dict2Anki).
Otherwise it will cause this problem.
默认模板改成：Dict2Anki

**Comment by DrSkyeagle** [comment]
默认模板要怎么改成Dict2Anki啊，不明白
