### ISSUE TITLE
[已解决]同步报错

### ISSUE THREAD

**Issue by xuwa** [megachweng/Dict2Anki#30]
请问一下，默认模版哪里设置？
每次都是login成功，sync报错：
一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
File "C:\Users\xuwa\AppData\Roaming\Anki2\addons\Dict2Anki\window.py", line 297, in __startSync
self.lastWordList = self.__getLastWordList()
File "C:\Users\xuwa\AppData\Roaming\Anki2\addons\Dict2Anki\window.py", line 334, in __getLastWordList
cursor.execute("select terms from history where deck='%s' and dictionary = '%d' order by id desc limit 0, 1" % (deck, dictionary))
sqlite3.OperationalError: no such column: deck

**Comment by xuwa** [comment]
果然还是dict2anki.db惹的祸，删掉就会好了。

**Comment by megachweng** [comment]
@xuwa 是这样的，同步信息都保存在那个里面
等anki 基于python3和qt5版本出来之后再重写一下插件
