### ISSUE TITLE
同步报了一个错误，不过单词都同步过来了

### ISSUE THREAD

**Issue by xuwa** [megachweng/Dict2Anki#31]
一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\xuwa\AppData\Roaming\Anki2\addons\Dict2Anki\worker.py", line 170, in run
    urllib.urlretrieve(self.imageUrls[current][1], "MG-" + self.imageUrls[current][0] + '.jpg')
  File "urllib.py", line 98, in urlretrieve
  File "urllib.py", line 289, in retrieve
urllib.ContentTooShortError: retrieval incomplete: got only 9777 out of 14064 bytes

**Comment by megachweng** [comment]
这个是图片下载网络出现了点问题，可以试试新版[v5.0.0](https://ankiweb.net/shared/info/1284759083)的插件
