### ISSUE TITLE
单词无法同步，卡片无法建立。

### ISSUE THREAD

**Issue by CarpZheng** [megachweng/Dict2Anki#35]
点击单词同步之后出现这些，不知道是什么意思？
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\Dict2Anki\window.py", line 302, in __startSync
    self.__processNote(self.lookUpedTerms,self.comparedWordList['deleted'])
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\Dict2Anki\window.py", line 411, in __processNote
    Note(lookUpedTerms,deleteWords,syncSettings).processNote(self.syncTo.currentText())
  File "C:\Users\Administrator\AppData\Roaming\Anki2\addons\Dict2Anki\note.py", line 131, in processNote
    note['term'] = term['term']
  File "anki\notes.py", line 101, in __setitem__
  File "anki\notes.py", line 95, in _fieldOrd
KeyError: 'term'

**Comment by CarpZheng** [comment]
之前我增加了新的记忆库，命名为“听力单词”，在插件导入选项中选择这个记忆库导入一直处于导入失败状态，而在我将插件导入选项中单词导入的记忆库改为默认之后，导出就成功了，目前只能用这个方法解决这个问题，之后可以通过这个默认的记忆库，再将卡片所属记忆库更改为“听力单词”，此外在anki插件下载界面，有几个评论描述遇到了和我一样的问题，希望作者可以尽快解决这个问题，十分感谢！

**Comment by megachweng** [comment]
非常抱歉，最近有很多事情，肯定会在空闲时间重构一下代码的，感谢你的反馈
