### ISSUE TITLE
插件报错：AttributeError: 'module' object has no attribute '_create_unverified_context'

### ISSUE THREAD

**Issue by fqzhou** [megachweng/Dict2Anki#40]
插件在Anki启动时报错，
![image](https://user-images.githubusercontent.com/10046680/47474588-3731f300-d84a-11e8-8163-6d33e2d09df8.png)
详情如下：

一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt\addons.py", line 41, in loadAddons
  File "C:\Users\fqzhou\AppData\Roaming\Anki2\addons\PluginEntry.py", line 11, in <module>
    from Dict2Anki.window import Window
  File "C:\Users\fqzhou\AppData\Roaming\Anki2\addons\Dict2Anki\window.py", line 22, in <module>
    ssl._create_default_https_context = ssl._create_unverified_context
AttributeError: 'module' object has no attribute '_create_unverified_context'

**Comment by megachweng** [comment]
新版插件正在开发中，这个问题是python2.x ssl问题，新版插件正在开发中
