### ISSUE TITLE
Dict2Anki3.0报错

### ISSUE THREAD

**Issue by Fengzjiyi** [megachweng/Dict2Anki#41]
一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\14016\AppData\Roaming\Anki2\addons\Dict2Anki\window.py", line 302, in __startSync
    self.__processNote(self.lookUpedTerms,self.comparedWordList['deleted'])
  File "C:\Users\14016\AppData\Roaming\Anki2\addons\Dict2Anki\window.py", line 411, in __processNote
    Note(lookUpedTerms,deleteWords,syncSettings).processNote(self.syncTo.currentText())
  File "C:\Users\14016\AppData\Roaming\Anki2\addons\Dict2Anki\note.py", line 131, in processNote
    note['term'] = term['term']
  File "anki\notes.py", line 101, in __setitem__
  File "anki\notes.py", line 95, in _fieldOrd
KeyError: 'term'

**Comment by megachweng** [comment]
新版插件正在开发中
