### ISSUE TITLE
一个插件发生了错误。 请把它报告在插件的论坛上:

### ISSUE THREAD

**Issue by 1996lijiangnan** [megachweng/Dict2Anki#44]
一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\lijiangnan\AppData\Roaming\Anki2\addons\Dict2Anki\window.py", line 302, in __startSync
    self.__processNote(self.lookUpedTerms,self.comparedWordList['deleted'])
  File "C:\Users\lijiangnan\AppData\Roaming\Anki2\addons\Dict2Anki\window.py", line 411, in __processNote
    Note(lookUpedTerms,deleteWords,syncSettings).processNote(self.syncTo.currentText())
  File "C:\Users\lijiangnan\AppData\Roaming\Anki2\addons\Dict2Anki\note.py", line 131, in processNote
    note['term'] = term['term']
  File "anki\notes.py", line 101, in __setitem__
  File "anki\notes.py", line 95, in _fieldOrd
KeyError: 'term'
ANKI版本为2.0，同步时报错，请问是什么原因？

**Comment by megachweng** [comment]
你好Anki2.0.x版本的插件已经停止维护，如果可以请升级Anki到[2.1.x](https://apps.ankiweb.net/#windows)版，使用刚刚发布的[Dict2Anki v5.0.0](https://ankiweb.net/shared/info/1284759083)
