### ISSUE TITLE
无法同步

### ISSUE THREAD

**Issue by xinsu626** [megachweng/Dict2Anki#63]
单词无法同步。
Anki 版本是2.1.3，Dict2Anki V6.0，Mac，有道词典。

错误：
[12/06/2019 23:20:28][   ERROR] -- 'term' - (dict2Anki)Traceback (most recent call last):  File "anki/notes.py", line 93, in _fieldOrdKeyError: 'term'During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/Users/Library/Application Support/Anki2/addons21/1284759083/addon/addonWindow.py", line 452, in on_syncBtn_clicked    addNoteToDeck(deck, model, currentConfig, wordItemData)  File "/Users/Library/Application Support/Anki2/addons21/1284759083/addon/noteManager.py", line 123, in addNoteToDeck    newNote['term'] = oneQueryResult['term']  File "anki/notes.py", line 101, in __setitem__  File "anki/notes.py", line 95, in _fieldOrdKeyError: 'term'

**Comment by megachweng** [comment]
#60 应该是同样的问题

**Comment by xinsu626** [comment]
@megachweng 谢谢这么快的回复。问题已经解决了。

**Comment by megachweng** [comment]
不客气，请问是不是从Anki2.0版本时使用了老版插件，然后升级上来的呢，遇到很多次同样的问题了

**Comment by xinsu626** [comment]
不是的。我是这最近才开始用anki 2.1.3的。
