### ISSUE TITLE
无法同步 严重错误

### ISSUE THREAD

**Issue by Jaschenn** [megachweng/Dict2Anki#67]
点击查询没有问题，点击同步出现错误
错误日志如下：
```
[18/07/2019 22:52:28][   ERROR] -- 'term' - (dict2Anki)Traceback (most recent call last):  File "anki/notes.py", line 93, in _fieldOrdKeyError: 'term'During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/Users/jas/Library/Application Support/Anki2/addons21/1284759083/addon/addonWindow.py", line 452, in on_syncBtn_clicked    addNoteToDeck(deck, model, currentConfig, wordItemData)  File "/Users/jas/Library/Application Support/Anki2/addons21/1284759083/addon/noteManager.py", line 123, in addNoteToDeck    newNote['term'] = oneQueryResult['term']  File "anki/notes.py", line 101, in __setitem__  File "anki/notes.py", line 95, in _fieldOrdKeyError: 'term'
```
我不知道如何解决这个问题，特地来寻求帮助

**Comment by megachweng** [comment]
#60 可能是同样的问题

**Comment by Jaschenn** [comment]
感谢。
原因是之前安装过生成的模版没有清除，因此只需清除掉或者是使用新的版本就可以解决问题

再次表示感谢。
