### ISSUE TITLE
Win10 欧路 Anki2.0.48报错

### ISSUE THREAD

**Issue by 36jerry** [megachweng/Dict2Anki#7]
最近欧路有大版本更新，不知是不是这个原因

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\Gamo\AppData\Roaming\Anki2\addons\Dict2Anki.py", line 211, in sync
    current = self.getCurrent()
  File "C:\Users\Gamo\AppData\Roaming\Anki2\addons\Dict2Anki.py", line 288, in getCurrent
    cursor.execute(query)
sqlite3.DatabaseError: file is encrypted or is not a database

**Comment by megachweng** [comment]
看起来是这样，这个程式会读取欧路的本地数据库，我去排查一下

**Comment by megachweng** [comment]
看起来欧路词典将本地的数据库加密了，试试看破解密码，不行的话联系官方看能不能解决

**Comment by megachweng** [comment]
@36jerry Dict2Anki v3版本已经可以在最新的欧路词典下正常使用。
请根据README提示安装，感谢你的支持
