### ISSUE TITLE
有道词典无法获取单词列表，不出现登录窗口

### ISSUE THREAD

**Issue by kchen0x** [megachweng/Dict2Anki#72]
log：

```
[12/11/2019 17:12:11][   ERROR] -- HTTPConnectionPool(host='127.0.0.1', port=7890): Max retries exceeded with url: http://account.youdao.com/login?service=dict&back_url=http://dict.youdao.com/wordbook/wordlist%3Fkeyfrom%3Dnull (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))) - (dict2Anki)Traceback (most recent call last):  File "urllib3/connectionpool.py", line 600, in urlopen  File "urllib3/connectionpool.py", line 384, in _make_request  File "<string>", line 2, in raise_from  File "urllib3/connectionpool.py", line 380, in _make_request  File "http/client.py", line 1331, in getresponse  File "http/client.py", line 297, in begin  File "http/client.py", line 266, in _read_statushttp.client.RemoteDisconnected: Remote end closed connection without responseDuring handling of the above exception, another exception occurred:Traceback (most recent call last):  File "requests/adapters.py", line 449, in send  File "urllib3/connectionpool.py", line 638, in urlopen  File "urllib3/util/retry.py", line 398, in incrementurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=7890): Max retries exceeded with url: http://account.youdao.com/login?service=dict&back_url=http://dict.youdao.com/wordbook/wordlist%3Fkeyfrom%3Dnull (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "/Users/kchen/Library/Application Support/Anki2/addons21/1284759083/addon/workers.py", line 47, in run    loginState = self.checkFn(self.cookie)  File "/Users/kchen/Library/Application Support/Anki2/addons21/1284759083/addon/dictionary/youdao.py", line 36, in checkCookie    rsp = requests.get('http://dict.youdao.com/wordbook/wordlist', cookies=cookie, headers=self.headers)  File "requests/api.py", line 75, in get  File "requests/api.py", line 60, in request  File "requests/sessions.py", line 524, in request  File "requests/sessions.py", line 659, in send  File "requests/sessions.py", line 659, in <listcomp>  File "requests/sessions.py", line 238, in resolve_redirects  File "requests/sessions.py", line 637, in send  File "requests/adapters.py", line 510, in sendrequests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=7890): Max retries exceeded with url: http://account.youdao.com/login?service=dict&back_url=http://dict.youdao.com/wordbook/wordlist%3Fkeyfrom%3Dnull (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
```

**Comment by wd** [comment]
Caused by ProxyError('Cannot connect to proxy.',

**Comment by megachweng** [comment]
尝试关闭代理软件重试

**Comment by kchen0x** [comment]
It works. 👍
