### ISSUE TITLE
报错求助

### ISSUE THREAD

**Issue by bosconb** [megachweng/Dict2Anki#78]
导入后显示也异常，我用的是

欧陆 3.9.3 (1036)增强版+anki版本 2.1.19 (3c8690ae)+dict2anki最新6.1.1

![image](https://user-images.githubusercontent.com/47100031/73961049-db0fb700-4946-11ea-95e2-dd94d15842b3.png)

[07/02/2020 01:03:22][   ERROR] -- list index out of range - (dict2Anki.queryApi.youdao)Traceback (most recent call last):  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 174, in query    queryResult = cls.parser(rsp.text, word).result  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 150, in result    'BrEPhonetic': self.BrEPhonetic,  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 85, in BrEPhonetic    return self.pronunciations['BrEPhonetic']  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 66, in pronunciations    pron['BrEUrl'] = url + links[0]['data-rel']IndexError: list index out of range
[07/02/2020 01:03:23][   ERROR] -- list index out of range - (dict2Anki.queryApi.youdao)Traceback (most recent call last):  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 174, in query    queryResult = cls.parser(rsp.text, word).result  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 150, in result    'BrEPhonetic': self.BrEPhonetic,  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 85, in BrEPhonetic    return self.pronunciations['BrEPhonetic']  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 66, in pronunciations    pron['BrEUrl'] = url + links[0]['data-rel']IndexError: list index out of range
[07/02/2020 01:03:23][   ERROR] -- list index out of range - (dict2Anki.queryApi.youdao)Traceback (most recent call last):  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 174, in query    queryResult = cls.parser(rsp.text, word).result  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 150, in result    'BrEPhonetic': self.BrEPhonetic,  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 85, in BrEPhonetic    return self.pronunciations['BrEPhonetic']  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 66, in pronunciations    pron['BrEUrl'] = url + links[0]['data-rel']IndexError: list index out of range
[07/02/2020 01:03:24][   ERROR] -- list index out of range - (dict2Anki.queryApi.youdao)Traceback (most recent call last):  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 174, in query    queryResult = cls.parser(rsp.text, word).result  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 150, in result    'BrEPhonetic': self.BrEPhonetic,  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 85, in BrEPhonetic    return self.pronunciations['BrEPhonetic']  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 66, in pronunciations    pron['BrEUrl'] = url + links[0]['data-rel']IndexError: list index out of range
[07/02/2020 01:03:24][   ERROR] -- list index out of range - (dict2Anki.queryApi.youdao)Traceback (most recent call last):  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 174, in query    queryResult = cls.parser(rsp.text, word).result  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 150, in result    'BrEPhonetic': self.BrEPhonetic,  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 85, in BrEPhonetic    return self.pronunciations['BrEPhonetic']  File "/Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py", line 61, in pronunciations    pron['BrEPhonetic'] = phons[0].get_text(strip=True)IndexError: list index out of range

**Comment by wd** [comment]
把 Anki 关闭了，然后你用这个文件  https://raw.githubusercontent.com/megachweng/Dict2Anki/11eab355f98e434f8c3312a8e4633d1bb4774813/addon/queryApi/eudict.py 替换你的自己电脑上面的 /Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py  ，然后再打开 anki 看看。

可能你需要去 Anki 里面先删除导入出问题的 offense 这个词，要不这个插件不会再次导入。

**Comment by bosconb** [comment]
> 把 Anki 关闭了，然后你用这个文件 https://raw.githubusercontent.com/megachweng/Dict2Anki/11eab355f98e434f8c3312a8e4633d1bb4774813/addon/queryApi/eudict.py 替换你的自己电脑上面的 /Users/dazkarieh/Library/Application Support/Anki2/addons21/1284759083/addon/queryApi/eudict.py ，然后再打开 anki 看看。
> 
> 可能你需要去 Anki 里面先删除导入出问题的 offense 这个词，要不这个插件不会再次导入。

牛牛牛，完美解决，太感谢了！
