### ISSUE TITLE
同步时发生错误

### ISSUE THREAD

**Issue by toysoldiers000** [megachweng/Dict2Anki#87]
[29/07/2020 21:27:26][   ERROR] -- InvalidInput { info: "1 field required" } - (dict2Anki)Traceback (most recent call last):  File "C:\Users\deime\AppData\Roaming\Anki2\addons21\1284759083\addon\addonWindow.py", line 442, in on_syncBtn_clicked    model = getOrCreateModel(MODEL_NAME)  File "C:\Users\deime\AppData\Roaming\Anki2\addons21\1284759083\addon\noteManager.py", line 56, in getOrCreateModel    mw.col.models.add(newModel)  File "lib\site-packages\anki\models.py", line 220, in add  File "lib\site-packages\anki\models.py", line 87, in save  File "lib\site-packages\anki\models.py", line 231, in update  File "lib\site-packages\anki\rsbackend_gen.py", line 414, in add_or_update_notetype  File "lib\site-packages\anki\rsbackend.py", line 265, in _run_commandanki.rsbackend.InvalidInput: InvalidInput { info: "1 field required" }

**Comment by toysoldiers000** [comment]
更换了Anki客户端为windows 2.1.26 版本问题解决，应该是新版本和插件不兼容的问题
