### ISSUE TITLE
Mac系统上插件报错，并且同步失败

### ISSUE THREAD

**Issue by halatony** [megachweng/Dict2Anki#88]
[03/08/2020 07:56:47][   ERROR] -- InvalidInput { info: "1 field required" } - (dict2Anki)Traceback (most recent call last):  File "/Users/yujie/Library/Application Support/Anki2/addons21/1284759083/addon/addonWindow.py", line 442, in on_syncBtn_clicked    model = getOrCreateModel(MODEL_NAME)  File "/Users/yujie/Library/Application Support/Anki2/addons21/1284759083/addon/noteManager.py", line 56, in getOrCreateModel    mw.col.models.add(newModel)  File "anki/models.py", line 220, in add  File "anki/models.py", line 87, in save  File "anki/models.py", line 231, in update  File "anki/rsbackend_gen.py", line 414, in add_or_update_notetype  File "anki/rsbackend.py", line 265, in _run_commandanki.rsbackend.InvalidInput: InvalidInput { info: "1 field required" }

**Comment by toysoldiers000** [comment]
你试试更换下之前的Anki客户端版本（我改用了2.1.26，就可以用了），应该是新版本和插件不兼容
