### ISSUE TITLE
Anki 2.1.33 同步失败

### ISSUE THREAD

**Issue by zilongshanren** [megachweng/Dict2Anki#91]
```
[15/09/2020 10:34:30][   DEBUG] -- {'term': 'imbue', 'definition': [], 'phrase': [], 'image': None, 'sentence': [], 'BrEPhonetic': "/ɪm'bjuː/", 'AmEPhonetic': "/ɪm'bjʊ/", 'BrEPron': 'https://api.frdic.com/api/v2/speech/speakweb?langid=en&voicename=en_uk_male&txt=QYNaW1idWU%3d', 'AmEPron': 'https://api.frdic.com/api/v2/speech/speakweb?langid=en&voicename=en_us_female&txt=QYNaW1idWU%3d'} - (dict2Anki.queryApi.eudict)
[15/09/2020 10:34:30][    INFO] -- 查询成功: imbue -- {'term': 'imbue', 'definition': [], 'phrase': [], 'image': None, 'sentence': [], 'BrEPhonetic': "/ɪm'bjuː/", 'AmEPhonetic': "/ɪm'bjʊ/", 'BrEPron': 'https://api.frdic.com/api/v2/speech/speakweb?langid=en&voicename=en_uk_male&txt=QYNaW1idWU%3d', 'AmEPron': 'https://api.frdic.com/api/v2/speech/speakweb?langid=en&voicename=en_us_female&txt=QYNaW1idWU%3d'} - (dict2Anki.workers.QueryWorker)
[15/09/2020 10:34:31][    INFO] -- 当前设置:{'selectedDict': 0, 'selectedApi': 1, 'selectedGroup': [['全部生词本', '我的生词本'], []], 'deck': '欧陆字典', 'username': '', 'password': *******, 'cookie': *******, 'definition': True, 'sentence': True, 'image': True, 'phrase': True, 'AmEPhonetic': True, 'BrEPhonetic': True, 'BrEPron': False, 'AmEPron': False, 'noPron': True} - (dict2Anki)
[15/09/2020 10:34:31][    INFO] -- 保存配置项:{'selectedDict': 0, 'selectedApi': 1, 'selectedGroup': [['全部生词本', '我的生词本'], []], 'deck': '欧陆字典', 'definition': True, 'sentence': True, 'image': True, 'phrase': True, 'AmEPhonetic': True, 'BrEPhonetic': True, 'BrEPron': False, 'AmEPron': False, 'noPron': True, 'credential': [{'username': '', 'password': *******, 'cookie': *******}, {'username': '', 'password': *******, 'cookie': *******}]} - (dict2Anki)
[15/09/2020 10:34:31][    INFO] -- 创建新模版:Dict2Anki-v6.1.3 - (dict2Anki.noteManager)
[15/09/2020 10:34:31][   ERROR] -- InvalidInput { info: "1 field required" } - (dict2Anki)Traceback (most recent call last):  File "C:\Users\lionqu\AppData\Roaming\Anki2\addons21\1284759083\addon\addonWindow.py", line 442, in on_syncBtn_clicked    model = getOrCreateModel(MODEL_NAME)  File "C:\Users\lionqu\AppData\Roaming\Anki2\addons21\1284759083\addon\noteManager.py", line 56, in getOrCreateModel    mw.col.models.add(newModel)  File "anki\models.py", line 220, in add  File "anki\models.py", line 87, in save  File "anki\models.py", line 231, in update  File "anki\rsbackend_gen.py", line 414, in add_or_update_notetype  File "anki\rsbackend.py", line 265, in _run_commandanki.rsbackend.InvalidInput: InvalidInput { info: "1 field required" }
```

**Comment by zilongshanren** [comment]
更换了Anki客户端为windows 2.1.26 版本问题解决，应该是新版本和插件不兼容的问题

**Comment by cythb** [comment]
https://github.com/megachweng/Dict2Anki/pull/93
