### ISSUE TITLE
有道词典无法同步  同步网页无法打开  进度条一直显示在加载  从3月10日开始发现  希望处理 感谢

### ISSUE THREAD

**Issue by yisa3** [megachweng/Dict2Anki#97]
有道词典无法同步  同步网页无法打开  进度条一直显示在加载  从3月10日开始发现  希望处理 感谢
日志如下
[14/03/2021 11:54:44][    INFO] -- 当前设置:{'selectedDict': 1, 'selectedApi': 0, 'selectedGroup': None, 'deck': 'a', 'username': '', 'password': *******, 'cookie': *******, 'definition': True, 'sentence': True, 'image': True, 'phrase': True, 'AmEPhonetic': True, 'BrEPhonetic': True, 'BrEPron': False, 'AmEPron': False, 'noPron': True} - (dict2Anki)
[14/03/2021 11:54:44][    INFO] -- 保存配置项:{'selectedDict': 1, 'selectedApi': 0, 'selectedGroup': None, 'deck': 'a', 'definition': True, 'sentence': True, 'image': True, 'phrase': True, 'AmEPhonetic': True, 'BrEPhonetic': True, 'BrEPron': False, 'AmEPron': False, 'noPron': True, 'credential': [{'username': '', 'password': *******, 'cookie': *******}, {'username': '', 'password': *******, 'cookie': *******}]} - (dict2Anki)
[14/03/2021 11:54:48][   ERROR] -- 'code' - (dict2Anki)Traceback (most recent call last):  File "C:\Users\***\AppData\Roaming\Anki2\addons21\1284759083\addon\workers.py", line 47, in run    loginState = self.checkFn(self.cookie)  File "C:\Users\***\AppData\Roaming\Anki2\addons21\1284759083\addon\dictionary\youdao.py", line 39, in checkCookie    if rsp.json()['code'] == 0:KeyError: 'code'

**Comment by megachweng** [comment]
可以试一下在 `设置` 页面把cookie清空，重新登陆

**Comment by megachweng** [comment]
fixed 2ad9c171bb5bfcdea8990c149e0b9bcfd5cb0dd7
